#!/usr/bin/env python3

list_of_links = [
    'https://thecleverprogrammer.com/2020/07/20/next-word-prediction-model/',
    'https://thecleverprogrammer.com/2020/07/22/image-segmentation/',
    'https://thecleverprogrammer.com/2020/05/23/data-science-project-dna-sequencing-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/01/chatbot-with-machine-learning-and-python/',
    'https://thecleverprogrammer.com/2020/06/12/sms-spam-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/29/covid-19-cases-prediction-with-python/',
    'https://thecleverprogrammer.com/2020/07/12/customer-segmentation/',
    'https://thecleverprogrammer.com/2020/11/16/apriori-algorithm-using-python/',
    'https://thecleverprogrammer.com/2020/08/10/translate-using-python/',
    'https://thecleverprogrammer.com/2020/08/26/image-recognition-with-machine-learning-using-pytorch/',
    'https://thecleverprogrammer.com/2020/08/16/fashion-recommendation-system/',
    'https://thecleverprogrammer.com/2020/08/06/whatsapp-group-chat-analysis/',
    'https://thecleverprogrammer.com/2020/08/14/keyword-research-with-python/',
    'https://thecleverprogrammer.com/2020/12/24/number-plate-detection-with-python/',
    'https://thecleverprogrammer.com/2020/09/04/xgboost-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/12/network-security-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/16/emotion-detection-model/',
    'https://thecleverprogrammer.com/2020/07/20/next-word-prediction-model/',
    'https://thecleverprogrammer.com/2020/08/31/text-classification-with-tensorflow-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/09/data-science-project-on-area-and-population/',
    'https://thecleverprogrammer.com/2020/05/09/data-science-project-on-text-and-annotations/',
    'https://thecleverprogrammer.com/2020/11/29/chatbot-projects-with-python/',
    'https://thecleverprogrammer.com/2020/07/22/face-landmarks-detection/',
    'https://thecleverprogrammer.com/2020/09/19/analyze-call-records-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/25/named-entity-recognition-with-python/',
    'https://thecleverprogrammer.com/2020/11/22/deep-learning-projects-with-python/',
    'https://thecleverprogrammer.com/2020/09/07/neural-network-with-python-code/',
    'https://thecleverprogrammer.com/2020/11/28/youtube-trending-videos-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/08/24/summarize-text-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/09/data-science-project-on-handwritten-digits/',
    'https://thecleverprogrammer.com/2020/05/20/data-science-project-heart-disease-prediction-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/11/rainfall-prediction-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/21/employee-attrition-prediction-with-python/',
    'https://thecleverprogrammer.com/2020/10/10/handwriting-recognition-with-python/',
    'https://thecleverprogrammer.com/2020/11/17/face-mask-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/08/data-science-project-on-president-heights/',
    'https://thecleverprogrammer.com/2020/07/19/image-classification-with-ann/',
    'https://thecleverprogrammer.com/2020/08/02/gender-classification-model/',
    'https://thecleverprogrammer.com/2020/12/22/object-detection-with-python/',
    'https://thecleverprogrammer.com/2020/07/25/image-filtering-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/24/flower-recognition-with-python/',
    'https://thecleverprogrammer.com/2020/12/23/gold-price-prediction-with-python/',
    'https://thecleverprogrammer.com/2020/09/09/analyze-healthcare-data-with-python/',
    'https://thecleverprogrammer.com/2020/10/22/create-an-audiobook-with-python/',
    'https://thecleverprogrammer.com/2020/09/09/nlp-for-other-languages-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/15/income-classification-with-python/',
    'https://thecleverprogrammer.com/2020/10/23/barcode-and-qr-code-reader-with-python/',
    'https://thecleverprogrammer.com/2020/10/09/ridge-and-lasso-regression-with-python/',
    #'https://thecleverprogrammer.com/2020/07/18/fake-news-detection-model/',
    'https://thecleverprogrammer.com/2020/06/10/credit-card-fraud-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/20/hand-gesture-recognition-with-python/',
    'https://thecleverprogrammer.com/2020/07/20/data-augmentation-in-deep-learning/',
    'https://thecleverprogrammer.com/2020/05/25/algorithmic-trading-strategy-with-machine-learning-and-python/',
    'https://thecleverprogrammer.com/2020/09/14/3d-video-with-python/',
    'https://thecleverprogrammer.com/2020/08/30/image-classification-with-tensorflow-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/30/predict-weather-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/27/classify-nationalities-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/23/analyze-ipl-with-python/',
    'https://thecleverprogrammer.com/2020/12/01/keyword-extraction-with-python/',
    'https://thecleverprogrammer.com/2020/07/26/openai-gym-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/26/data-science-project-predict-customer-churn-with-python-and-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/08/data-science-project-on-birth-rate-analysis/',
    'https://thecleverprogrammer.com/2020/11/27/regression-projects-with-python/',
    'https://thecleverprogrammer.com/2020/08/06/whatsapp-group-chat-analysis/',
    'https://thecleverprogrammer.com/2020/09/28/predict-tinder-matches-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/10/08/language-classification-with-python/',
    'https://thecleverprogrammer.com/2020/07/12/employee-turnover-prediction/',
    'https://thecleverprogrammer.com/2020/07/16/pytorch-for-deep-learning/',
    'https://thecleverprogrammer.com/2020/05/15/data-science-project-on-extracting-hog-features/',
    'https://thecleverprogrammer.com/2020/11/14/stock-price-prediction-using-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/27/daily-births-forecasting-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/08/genetic-algorithm-with-python/',
    'https://thecleverprogrammer.com/2020/07/01/time-series-analysis-and-forecasting-with-python/',
    'https://thecleverprogrammer.com/2020/11/08/landmark-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/24/machine-learning-project-artificial-neural-networks/',
    'https://thecleverprogrammer.com/2020/09/22/predict-ipl-winner-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/14/3d-video-with-python/',
    'https://thecleverprogrammer.com/2020/11/25/gender-classification-with-python/',
    'https://thecleverprogrammer.com/2020/11/29/machine-learning-projects-on-future-prediction/',
    'https://thecleverprogrammer.com/2020/05/14/data-science-project-on-classification-of-text/',
    'https://thecleverprogrammer.com/2020/11/12/earthquake-prediction-model-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/29/house-price-prediction-with-python/',
    'https://thecleverprogrammer.com/2020/08/18/telegram-bot-with-python/',
    'https://thecleverprogrammer.com/2020/09/08/predict-migration-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/10/24/topic-modeling-with-python/',
    'https://thecleverprogrammer.com/2020/09/13/image-features-extraction-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/10/heart-disease-prediction-using-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/31/opencv-with-python-tutorial/',
    'https://thecleverprogrammer.com/2020/10/07/visualize-a-solar-system-with-python/',
    'https://thecleverprogrammer.com/2020/11/30/amazon-bestselling-books-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/09/03/abc-analysis-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/21/highest-paid-athletes-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/11/23/air-quality-index-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/05/26/data-science-project-san-francisco-crime-analysis/',
    'https://thecleverprogrammer.com/2020/12/08/language-translation-with-python/',
    'https://thecleverprogrammer.com/2020/07/13/predict-diabetes-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/18/restaurant-recommendation-system-with-python/',
    'https://thecleverprogrammer.com/2020/12/27/real-time-face-mask-detection-with-python/',
    'https://thecleverprogrammer.com/2020/08/29/time-series-with-lstm-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/23/ipl-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/07/28/machine-translation-model/',
    'https://thecleverprogrammer.com/2020/12/26/netflix-recommendation-system-with-python/',
    #'https://thecleverprogrammer.com/2020/05/22/data-science-project-fake-news-classification/',
    'https://thecleverprogrammer.com/2020/07/16/nlp-for-whatsapp-chats/',
    'https://thecleverprogrammer.com/2020/11/09/plastic-users-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/08/10/translate-using-python/',
    'https://thecleverprogrammer.com/2020/08/20/contact-tracing-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/11/data-science-project-stock-price-prediction-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/07/22/image-segmentation/',
    'https://thecleverprogrammer.com/2020/09/15/send-emails-with-python/',
    'https://thecleverprogrammer.com/2020/06/11/weather-forecasting-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/28/galaxy-classification-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/29/fake-currency-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/31/diamonds-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/12/18/machine-learning-project-walkthrough-with-python/',
    'https://thecleverprogrammer.com/2020/10/09/graph-algorithms-with-python/',
    'https://thecleverprogrammer.com/2020/05/17/data-science-project-email-spam-detection-with-machine-learning/',
    #'https://thecleverprogrammer.com/2020/08/24/otp-verification-gui-with-python/',
    'https://thecleverprogrammer.com/2020/09/21/predict-car-prices-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/21/data-science-project-student-performance-analysis-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/04/online-shopping-intention-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/11/12/outlier-detection-with-python/',
    'https://thecleverprogrammer.com/2020/05/22/data-science-project-on-fifa-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/12/20/text-generation-with-python/',
    'https://thecleverprogrammer.com/2020/07/28/audio-feature-extraction/',
    'https://thecleverprogrammer.com/2020/11/14/breast-cancer-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/08/data-science-project-on-time-series/',
    'https://thecleverprogrammer.com/2020/08/28/binary-search-algorithm-with-python/',
    'https://thecleverprogrammer.com/2020/05/26/data-science-project-supermarket-sales-analysis/',
    'https://thecleverprogrammer.com/2020/08/25/titanic-survival-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/15/amazon-product-reviews-sentiment-analysis-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/12/05/sign-language-classification-with-python/',
    'https://thecleverprogrammer.com/2020/09/26/tiktok-algorithm-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/07/machine-learning-in-5-lines-with-mindsdb/',
    'https://thecleverprogrammer.com/2020/10/04/autocorrect-with-python/',
    'https://thecleverprogrammer.com/2020/09/14/colour-recognition-with-python/',
    'https://thecleverprogrammer.com/2020/11/25/sentiment-analysis-projects-with-python/',
    'https://thecleverprogrammer.com/2020/09/07/rfm-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/08/21/deploy-a-chatbot-with-python/',
    'https://thecleverprogrammer.com/2020/05/20/data-science-project-movie-recommendation-system/',
    'https://thecleverprogrammer.com/2020/05/23/data-science-project-book-recommendation-system-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/23/data-science-project-bitcoin-price-prediction-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/27/machine-learning-project-human-activity-recognition-using-smartphone-data/',
    'https://thecleverprogrammer.com/2020/08/30/how-to-create-a-package-with-python/',
    'https://thecleverprogrammer.com/2020/08/19/hate-speech-detection-model/',
    'https://thecleverprogrammer.com/2020/10/05/covid-19-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/12/03/network-graph-analysis-with-python/',
    'https://thecleverprogrammer.com/2020/09/16/api-with-python/',
    'https://thecleverprogrammer.com/2020/09/06/lung-segmentation-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/05/26/data-science-project-gdp-analysis/',
    'https://thecleverprogrammer.com/2020/07/22/face-landmarks-detection/',
    'https://thecleverprogrammer.com/2020/08/04/named-entity-recognition-ner/',
    'https://thecleverprogrammer.com/2020/07/28/machine-translation-model/',
    'https://thecleverprogrammer.com/2020/10/03/deepfake-detection-with-python/',
    'https://thecleverprogrammer.com/2020/08/04/named-entity-recognition-ner/',
    #'https://thecleverprogrammer.com/2020/09/29/google-search-algorithm-with-python/',
    'https://thecleverprogrammer.com/2020/11/26/classification-projects-with-python/',
    'https://thecleverprogrammer.com/2020/10/06/extract-text-from-pdf-using-python/',
    'https://thecleverprogrammer.com/2020/05/25/movie-reviews-sentiment-analysis-binary-classification-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/11/23/recommendation-system-projects-with-python/',
    'https://thecleverprogrammer.com/2020/09/24/instagram-filters-with-python/',
    'https://thecleverprogrammer.com/2020/10/29/age-and-gender-detection-with-python/',
    'https://thecleverprogrammer.com/2020/11/21/covid-19-projects-with-python-and-machine-learning/',
    'https://thecleverprogrammer.com/2020/10/05/title-generator-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/02/gender-classification-model/',
    'https://thecleverprogrammer.com/2020/11/22/pneumonia-detection-with-python/',
    'https://thecleverprogrammer.com/2020/09/02/predict-fuel-efficiency-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/09/30/pencil-sketch-with-python/',
    'https://thecleverprogrammer.com/2020/07/06/support-vector-machines-svm-in-machine-learning/',
    'https://thecleverprogrammer.com/2020/08/14/bar-chart-race-with-python/',
    'https://thecleverprogrammer.com/2020/10/01/predict-us-elections-with-python/',
    'https://thecleverprogrammer.com/2020/10/09/face-detection-with-python/',
    'https://thecleverprogrammer.com/2020/09/01/image-segmentation-with-python/',
    'https://thecleverprogrammer.com/2020/12/31/text-summarization-with-python/',
    'https://thecleverprogrammer.com/2020/08/04/fraud-detection-with-machine-learning/',
    'https://thecleverprogrammer.com/2020/07/20/binary-classification-model/',
    'https://thecleverprogrammer.com/2020/12/06/resume-screening-with-python/',
    #'https://thecleverprogrammer.com/2020/07/09/covid-19-detection/',
    'https://thecleverprogrammer.com/2020/12/18/spelling-correction-with-python/',
]

import logging as log
from re import findall
from requests import get
from time import sleep

markdown_list = ""

for link in list_of_links:
    log.warning("Getting %s" % link)
    response = get(link)

    log.warning("Response status code %u" % response.status_code)
    assert response.ok

    title = findall(r'\<title\>(.*)\<\/title\>', response.text)[0]
    log.warning("Extracted title from response '%s'" % title)
    assert title != ""

    markdown_item = "1. [%s](%s)\n" % (title, link)
    markdown_list += markdown_item
    log.warning("Added '%s' to list" % markdown_item)

print(markdown_list)

results_file_name = "result_list.md"
log.warning("Writting to %s" %  results_file_name)
with open(results_file_name, "w+") as f:
    f.write(markdown_list)
